### ISSUE TITLE
Issues?

### ISSUE THREAD

**Issue by frivoal** [w3c/type-samples#20]
The way this is currently being proposed, with images being filled as (labeled) issues makes it very easy to submit the images, and gives us a simple UI for sorting through things, both of which are really good features. On the other hand:
* only people with write access to the repo can set labels, which presumably exclude most submitters
* We cannot provide any view not supported by github issues, for example views with thumbnails.
* everything lives in github's databases, so we depend on them for hosting.

An alternative would be to take in the samples via pull request, and ask the submitter to provide the image and a metadata file in an agreed format with the relevant tags and possibly some descriptions. We could use that in a static site generator to create any kind of view we wanted. A big downside is that it would put quite a bit of overhead into submitting new images. Also, we would have to rebuild the search feature. That can be done without too much work on a static site (see here for an example: http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/), but we'd still have to do it. We'd also need to add some system for per-file discussion, which could be done with something like discuss.

A simple meta-data file, well suited for usage with the jekyll static site generated that github pages uses, could be something like this:
From issue https://github.com/w3c/type-samples/issues/12:
```yaml
---
title: Arabic, tatweel based justification
img: /imgs/123456789.jpg
langs: [ar]
scripts: [Arab]
tags: [justification]
medium: book
source: Asharq al Awsat, p1, 12 Dec 1994
---
Various examples of lines being stretched to fit justified columns
using simple baseline extensions.
```

From issue https://github.com/w3c/type-samples/issues/11:

```yaml
---
title: Arabic, bilingual sign justification
img: /imgs/0987654321.jpg
langs: [ar, en]
scripts: [Arab, Latn]
tags: [justification]
medium: signage
source: Oman, Muscat
---
The arabic text is stretched to be the same width as the latin text it corresponds to.
```

If this sounds interesting, I'm willing to give a shot at building a prototype/alpha version of that (and to maintain it if that's convincing enough that we're willing to adopt it).
